# Generated by Django 5.0 on 2026-01-24 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Chatbot name (min 3 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text="Brief description of the chatbot's purpose")),
                ('system_prompt', models.TextField(default='You are a helpful AI assistant. Answer questions based on the provided context.', help_text='System prompt that defines chatbot behavior')),
                ('temperature', models.FloatField(default=0.7, help_text='LLM temperature (0.0-1.0). Lower = more focused, Higher = more creative')),
                ('max_tokens', models.IntegerField(default=500, help_text='Maximum tokens in response')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the chatbot is active and can respond to queries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'db_table': 'chatbots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', help_text='Conversation title (auto-generated from first message)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbots.chatbot')),
                ('user', models.ForeignKey(blank=True, help_text='User who started the conversation (can be anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent the message', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('context_used', models.JSONField(blank=True, help_text='Retrieved document chunks used to generate response', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used for this message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbots.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['owner', '-created_at'], name='chatbots_owner_i_28b134_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['is_active'], name='chatbots_is_acti_863f36_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['chatbot', '-updated_at'], name='conversatio_chatbot_841232_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
    ]
