# Generated by Django 5.0 on 2026-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Time taken to generate this response in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='was_helpful',
            field=models.BooleanField(blank=True, help_text='User feedback on whether the response was helpful', null=True),
        ),
    ]
