# Generated by Django 5.0 on 2026-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_add_response_time_was_helpful_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='ai_model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='ai_provider',
            field=models.CharField(default='openai', max_length=50),
        ),
    ]
