# Generated by Django 5.0 on 2026-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_add_ai_model_to_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_avatars/'),
        ),
    ]
