# Generated by Django 5.0 on 2026-04-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_add_avatar_to_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='theme_colour',
            field=models.CharField(default='#B10000', max_length=7),
        ),
    ]
