# Generated by Django 5.0 on 2026-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0006_add_placeholder_widget_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='widget_height',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_width',
            field=models.PositiveIntegerField(default=380),
        ),
    ]
