# Generated by Django 5.0 on 2026-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0007_add_widget_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='allowed_domains',
            field=models.TextField(blank=True, default=''),
        ),
    ]
