# Generated by Django 5.0 on 2026-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_provider_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
